<?php
/**
 * @file
 * Main file for custom hooks.
 */



/**
 * Implements hook_theme().
 */
function users_feedback_theme($existing, $type, $theme, $path): array {
  return [
    'main' => [
      'variables' => [
        'main_form' => [],
      ],
    ],
  ];
}

function users_feedback_BasicFeedbackForm_alter(\Drupal\Core\Form\FormStateInterface $form_state) {
  $a = $form_state;
  $b = $form_state;
  return $a;
}
