<?php
/**
 * @file
 * Main file for custom hooks.
 */

use Drupal\Core\Form\FormStateInterface;


/**
 * Implements hook_theme().
 */
function users_feedback_theme($existing, $type, $theme, $path): array {
  return [
    'main' => [
      'variables' => [
        'main_form' => [],
      ],
    ],
    'custom_form' => [
      'render element' => 'form',
      'template' => 'custom-form',
    ],
  ];
}

///**
// * Implements hook_form_BASE_FORM_ID_alter().
// */
//function users_feedback_form_user_login_form_alter(&$form, FormStateInterface &$form_state) {
//  $form['#theme'] = ['feedback_form'];
//}

/**
 * Implements hook_theme_suggestions_alter
 */
function users_feedback_theme_suggestions_alter(array &$suggestions, array $variables)
{

  if (isset($variables['element']) && isset($variables['element']['#type']) && $variables['element']['#type'] == 'form') {
    $original_theme_hook = $variables['theme_hook_original'];

    $suggestions[] = $original_theme_hook . '__' . str_replace('-', '_', $variables['element']['#id']);
  }

  return $suggestions;

}
function users_feedback_form_BasicFeedbackForm_alter(&$form, FormStateInterface &$form_state) {
$form['#theme'] = ['custom_form'];
}
